## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [28]:
import pandas as pd

In [29]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [30]:
number_of_men = data['sex'].value_counts()
number_of_men

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [31]:
men_mean_age = data[data['sex'] == 'Male']['age'].mean()
men_mean_age

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [32]:
portion_USA = data[data['native-country'] == 'United-States'].shape[0]
portion_USA

29170

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [51]:
agg_functions = ["mean", "std"]
result_more50 = data[data['salary'] == '>50K']['age'].agg(agg_functions)
result_less50 = data[data['salary'] == '<=50K']['age'].agg(agg_functions)

print(f"result_more50:\n{result_more50}\n")
print(f"result_less50:\n{result_less50}")

result_more50:
mean    44.249841
std     10.519028
Name: age, dtype: float64

result_less50:
mean    36.783738
std     14.020088
Name: age, dtype: float64

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [76]:
edu = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
result = data[(data['salary'] == '>50K') & (data['education'].isin(edu))].shape[0] / data[(data['salary'] == '>50K')].shape[0] * 100
print(f"{result:.2f}% of people with salary more than 50K have higher education")

57.84% of people with salary more than 50K have higher education

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [85]:
result = data.groupby(['race', 'sex']).describe()
result

                               age                                          \
                             count       mean        std   min   25%   50%
race               sex
Amer-Indian-Eskimo Female    119.0  37.117647  13.114991  17.0  27.0  36.0
                   Male      192.0  37.208333  12.049563  17.0  28.0  35.0
Asian-Pac-Islander Female    346.0  35.089595  12.300845  17.0  25.0  33.0
                   Male      693.0  39.073593  12.883944  18.0  29.0  37.0
Black              Female   1555.0  37.854019  12.637197  17.0  28.0  37.0
                   Male     1569.0  37.682600  12.882612  17.0  27.0  36.0
Other              Female    109.0  31.678899  11.631599  17.0  23.0  29.0
                   Male      162.0  34.654321  11.355531  17.0  26.0  32.0
White              Female   8642.0  36.811618  14.329093  17.0  25.0  35.0
                   Male    19174.0  39.652498  13.436029  17.0  29.0  38.0

                                         fnlwgt                 ...  \
                             75%   max    count           mean  ...
race               sex                                          ...
Amer-Indian-Eskimo Female  46.00  80.0    119.0  112950.731092  ...
                   Male    45.00  82.0    192.0  125715.364583  ...
Asian-Pac-Islander Female  43.75  75.0    346.0  147452.075145  ...
                   Male    46.00  90.0    693.0  166175.865801  ...
Black              Female  46.00  90.0   1555.0  212971.387781  ...
                   Male    46.00  90.0   1569.0  242920.644997  ...
Other              Female  39.00  74.0    109.0  172519.642202  ...
                   Male    42.00  77.0    162.0  213679.104938  ...
White              Female  46.00  90.0   8642.0  183549.966906  ...
                   Male    49.00  90.0  19174.0  188987.386148  ...

                          capital-loss         hours-per-week             \
                                   75%     max          count       mean
race               sex
Amer-Indian-Eskimo Female          0.0  1721.0          119.0  36.579832
                   Male            0.0  1980.0          192.0  42.197917
Asian-Pac-Islander Female          0.0  2258.0          346.0  37.439306
                   Male            0.0  2457.0          693.0  41.468975
Black              Female          0.0  4356.0         1555.0  36.834084
                   Male            0.0  2824.0         1569.0  39.997451
Other              Female          0.0  1740.0          109.0  35.926606
                   Male            0.0  2179.0          162.0  41.851852
White              Female          0.0  4356.0         8642.0  36.296691
                   Male            0.0  3770.0        19174.0  42.668822


                                 std  min   25%   50%   75%   max
race               sex
Amer-Indian-Eskimo Female  11.046509  4.0  35.0  40.0  40.0  84.0
                   Male    11.596280  3.0  40.0  40.0  45.0  84.0
Asian-Pac-Islander Female  12.479459  1.0  35.0  40.0  40.0  99.0
                   Male    12.387563  1.0  40.0  40.0  45.0  99.0
Black              Female   9.419960  2.0  35.0  40.0  40.0  99.0
                   Male    10.909413  1.0  40.0  40.0  40.0  99.0
Other              Female  10.300761  6.0  30.0  40.0  40.0  65.0
                   Male    11.084779  5.0  40.0  40.0  40.0  98.0
White              Female  12.190951  1.0  30.0  40.0  40.0  99.0
                   Male    12.194633  1.0  40.0  40.0  50.0  99.0

[10 rows x 48 columns]

In [86]:
max_age = result.loc[('Asian-Pac-Islander', 'Male'), ('age', 'max')]
print(f"\nmax age of men with race 'Asian-Pac-Islander' is : {max_age}")

max age of men with race 'Asian-Pac-Islander' is : 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [87]:
marital_status = ['Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse']

result = data[(data['salary'] == '>50K') & (data['marital-status'].isin(marital_status))].shape[0] / data[(data['salary'] == '>50K')].shape[0] * 100
print(f"{result:.2f}% of people with salary more than 50K are married")

85.91% of people with salary more than 50K are married

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [98]:
max_hours_per_week = data['hours-per-week'].max()
print(f"max_hours_per_week: {max_hours_per_week}")

people_max_hours_per_week = data[data['hours-per-week'] == 99].shape[0]
print(f"people_max_hours_per_week: {people_max_hours_per_week}")

result = data[(data['hours-per-week'] == 99) & (data['salary'] == '>50K')].shape[0]/people_max_hours_per_week * 100
print(f"result: {result:.2f} %")

max_hours_per_week: 99
people_max_hours_per_week: 85
result: 29.41 %

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [111]:
result = data.groupby(['native-country', 'salary'])['hours-per-week'].mean().round(2)
result

native-country  salary
?               <=50K     40.16
                >50K      45.55
Cambodia        <=50K     41.42
                >50K      40.00
Canada          <=50K     37.91
                          ...
United-States   >50K      45.51
Vietnam         <=50K     37.19
                >50K      39.20
Yugoslavia      <=50K     41.60
                >50K      49.50
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [121]:
young = data[(data['age'] >= 16) & (data['age'] < 35)]
adult = data[(data['age'] >= 35) & (data['age'] < 70)]
retiree = data[(data['age'] >= 70) & (data['age'] < 100)]

def age_func(age):
    if 16 <= age < 35:
        return 'young'
    elif 35 <= age < 70:
        return 'adult'
    elif 70 <= age < 100:
        return 'retiree'
    
data['AgeGroup'] = data['age'].apply(age_func)
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,young
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,adult
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,adult
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,young
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,adult

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [130]:
result = data[data['salary'] == '>50K'].groupby(['AgeGroup']).size().reset_index(name = 'Count')
result

  AgeGroup  Count
0    adult   6240
1  retiree    113
2    young   1488

In [132]:
res = result.loc[result['Count'].idxmax()]
print(res['AgeGroup'])

adult

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [146]:
groups = data.groupby('occupation').agg(
    count=('occupation', 'size'),
    average_age=('age', 'mean'),
    all_hours_more_than_five=('hours-per-week', lambda x: (x > 5).all())
).reset_index()

print(groups)

def filter_func(df):
    return df[(df['average_age'] <= 40) & (df['all_hours_more_than_five'])]

filtered_groups = filter_func(groups)

print(f"\n{filtered_groups}")

           occupation  count  average_age  all_hours_more_than_five
0                   ?   1843    40.882800                     False
1        Adm-clerical   3770    36.964456                     False
2        Armed-Forces      9    30.222222                      True
3        Craft-repair   4099    39.031471                     False
4     Exec-managerial   4066    42.169208                     False
5     Farming-fishing    994    41.211268                     False
6   Handlers-cleaners   1370    32.165693                     False
7   Machine-op-inspct   2002    37.715285                     False
8       Other-service   3295    34.949621                     False
9     Priv-house-serv    149    41.724832                     False
10     Prof-specialty   4140    40.517633                     False
11    Protective-serv    649    38.953775                     False
12              Sales   3650    37.353973                     False
13       Tech-support    928    37.022629                     False
14   Transport-moving   1597    40.197871                     False

     occupation  count  average_age  all_hours_more_than_five
2  Armed-Forces      9    30.222222                      True